var tslib = require('tslib');
var moment = require('moment');
var lodash = tslib.__importStar(require('lodash'));
var arr = [1, 2, 3, 3, 4, 5];
var chunkArr = lodash.chunk(arr, 2);
var splitStr = lodash.split('a-b-c-d-e', '-', 5);
console.log(splitStr);
var str = lodash.replace("nishoo gupta", "nishoo", "gupta");
var names = 'nishoo';
var caps = lodash.capitalize(names);
var debNmev = lodash.deburr(names);
var todayss = moment().format("DD-MM-YYYY");
console.log(new Date(todayss));
console.log("todayss");
var today = moment();
var todays = today.format('yyyy-mm-dd');
today.format('YYYY-MM-DD');
today.add(7, 'days');
today.add(7, 'month');
var date = moment('1900-01-01', 'YYYY-MM-DD').fromNow();
var s = moment('01-01-1900', 'YYYY-MM-DD').fromNow();
moment('2021.01.01', 'YYYY.MM.DD').fromNow();
