let tslib = require('tslib');
let moment = require('moment');
let lodash = tslib.__importStar(require('lodash'));
let arr = [1, 2, 3, 3, 4, 5];
let chunkArr = lodash.chunk(arr, 2);
let today = moment();
let todays = today.format('yyyy-mm-dd');
today.format('YYYY-MM-DD');
today.add(7, 'days');
let date = moment('1900-01-01', 'YYYY-MM-DD').fromNow();
let s = moment('01-01-1900', 'YYYY-MM-DD').fromNow();
today.add(7, 'month');
let splitStr = lodash.split('a-b-c-d-e', '-', 5);
console.log(splitStr);
let str = lodash.replace("nishoo gupta", "nishoo", "gupta");
let names='nishoo';
let caps = lodash.capitalize(names);
let debNmev = lodash.deburr(names);
moment('2021.01.01', 'YYYY.MM.DD').fromNow();